### ISSUE TITLE
Test app doesnt detect, yet the banking apps do.

### ISSUE THREAD

**Issue by Absarock** [adrianmmiller/Hide-My-Applist-Guide#2]
I apologize I am not a programmer, I couldn't make HideMyApp list work.

I followed the guide provided by the dev, I made a blacklist template of every root app I could recognize, added 2 banking apps and app detector. App detector doesnt detect any problem. But still the banking apps detect root.

- Magisk Delta 25210 
- Lsposed for zygisk
- Both banking apps are in the denylist
- Zygisk turned on 
- MagiskHide turned on

Can someone assist me?
Am I doing something wrong?

![Screenshot_20230413-071913](https://user-images.githubusercontent.com/103369448/231661837-9748253e-7efe-45b7-b2c3-f926f4c254bb.jpg)
![Screenshot_20230413-071919](https://user-images.githubusercontent.com/103369448/231661842-ebf4efd9-656d-4ce9-b5ff-e4cd076e6924.jpg)
![Screenshot_20230413-071945](https://user-images.githubusercontent.com/103369448/231661845-f0816ad1-1efa-41a8-afa6-29776ca50baf.jpg)
![Screenshot_20230413-035744](https://user-images.githubusercontent.com/103369448/231661848-c98c90f4-3368-4290-a89c-7ceb4d906245.jpg)
![Screenshot (13 Apr 2023 7 25 32 am)](https://user-images.githubusercontent.com/103369448/231661963-f3e1ec54-dc22-4a42-ab93-81cb9879ded9.jpg)

**Comment by adrianmmiller** [comment]
Please confirm you:

1) created a blacklist, with magisk
then
2) applied that blacklist to banking apps
then
3) rebooted

if so, then you have done the correct thing

the one thing i can see in your screens is that you have a suspicious (eye)
for TWRP in abnormal environment in applist detector

please note that banking apps notably look for evidence of root in MANY
ways, one of them being the presence of a TWRP folder, because of course
TWRP only appears on rooted phones....so, my first tip, and one that
existed LONg before HMA was around and is a basic bank app hiding tip is to
rename your TWRP folder...

thats my guess, and its one that has nothing to do with HMA....

the only other thing to try is clearing app data for the banking apps, and
rebooting before trying again

worth pointing out theres a new version of the guide going up in a few
days, should be easier to follow, and offer an alternate setup (whitelist
mode)

and just a reminder, in general no dev offers support for any device where
lucky patcher is installed, so if you have further issues, you will need to
remove
that for further help

Adrian Miller

**Comment by Absarock** [comment]
- Yes, I did all the 3 steps
- Ok, I am removing the lucky patcher
- Renamed the TWRP folder in the root directory. Wouldnt that affect my recovery? It contains a file ".twrp s". I renamed that too
- Restarting the phone and clearing the storage everytime but it isnt working.
- Someone faced an issue with "Keytrade" app. I tried using that. Didnt work before hiding but worked fine after adding it to the "App Manage"

I know it may be requesting a lot, since I am not a contributor. But can youi download both the apps from playstore and try running them on your phone? Mooney and HBL

Thank you sm

**Comment by adrianmmiller** [comment]
You can still save backups to the renamed folder (renaming just the folder
is enough)

Downloaded both apps
Added both to deny list
Applied root blacklist to both apps
Rebooted

Test in blacklist template mode:

HBL: Loads fine i assume, i could sign in or sign up if i wanted...
Mooney: sits on its loading screen with yellow circle and mooney text for
about 20 seconds and the fc's...could be region limitation, could be root
detection

Test in whitelist mode:

HBL: Loads fine i assume, i could sign in or sign up if i wanted...
Mooney: sits on its loading screen with yellow circle and mooney text for
about 20 seconds and the fc's...could be region limitation, could be root
detection

Note: I am using Stable Magisk 26.0 with Shamiko module enabled (and
Enforce Deny List OFF)

You could try whitelist mode (this will be covered in updated guide in a
few days):

In HMA go to each banking app and toggle Work mode to Whitelist (this will
automatically remove the root blacklist template), then toggle exclude
system apps
Reboot.
Clear data for banking apps
Test

Nothing else i can do, theres no guarantee every banking app will work,
even with every current hiding method thrown at it, it may have a new
method of detecting
that we dont know about

**Comment by adrianmmiller** [comment]
You can still save backups to the renamed folder (renaming just the folder
is enough)

-Downloaded both apps
-Added both to deny list
-Applied root blacklist to both apps
-Rebooted

## Test in blacklist template mode:

**HBL:** Loads fine i assume, i could sign in or sign up if i wanted...

**Mooney:** sits on its loading screen with yellow circle and mooney text for about 20 seconds and the fc's...could be region limitation, could be root detection

## Test in whitelist mode:

**HBL:** Loads fine i assume, i could sign in or sign up if i wanted...
**Mooney:** sits on its loading screen with yellow circle and mooney text for about 20 seconds and the fc's...could be region limitation, could be root detection

---

**Note:** I am using Stable Magisk 26.0 with Shamiko module enabled (and Enforce Deny List OFF)

You could try whitelist mode (this will be covered in updated guide in a few days):

-In HMA go to each banking app and toggle Work mode to Whitelist (this will automatically remove the root blacklist template), then toggle exclude system apps
-Reboot.
-Clear data for banking apps
-Test

Nothing else i can do, theres no guarantee every banking app will work, even with every current hiding method thrown at it, it may have a new method of detecting that we dont know about. Its not uncommon for one banking app to work in Official Magisk and not in Delta and vice versa....but to fail in both means its usually the banking apps root detection doing something new

**Comment by Absarock** [comment]
Tried whitelist. Mooney still doesn't work (Its okay. I dont need it rn). But HBL works!

Thank you so much for your selfless cooperation.

Absarock
