### ISSUE TITLE
Trust wallet still detects root

### ISSUE THREAD

**Issue by NicolaSpadari** [adrianmmiller/Hide-My-Applist-Guide#4]
Hello, not sure if this is the place to ask for help, or the module repo, in that case I will move the issue there.

I followed the guide step by step and blocked root detection through Hide My Applist instead of Magisk's denylist and everything works so far.
The only issue is with Trust Wallet and another italian third party app I selected in the same exact way of the others.

Note: clearing app data / reinstalling those apps didn't help.
Here is my current configuration:

<table>
  <tr>
    <td>
      Trust wallet showing it detects root
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/25949931/235142763-d5dc6ca0-31ff-4146-8ea9-5a685848287b.jpeg" height="300" />
    </td>
  </tr>
  <tr>
    <td>
      "Root" blacklist apps
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/25949931/235143347-b5a5011c-b810-4572-89c4-e515326136bd.jpeg" height="300" />
      <img src="https://user-images.githubusercontent.com/25949931/235143352-a3076953-699b-42fa-b3bb-b223db52888e.jpeg" height="300" />
    </td>
  </tr>
  <tr>
    <td>
      Trust wallet with root blacklist applied
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/25949931/235143595-a831e38a-d9db-4dae-827f-591be40813eb.jpeg" height="300" />
      <img src="https://user-images.githubusercontent.com/25949931/235143597-42eaf6dc-4be6-4c01-90a0-6397ca322fcc.jpeg" height="300" />
    </td>
  </tr>
  <tr>
    <td>
      Applist detector test result
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/25949931/235143843-ef987c71-a507-4c38-a901-d20315fb5d35.jpeg" height="300" />
    </td>
  </tr>
  <tr>
    <td>
      LSposed status
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/25949931/235143896-0ead4490-6557-49da-9688-fe24229b8227.jpeg" height="300" />
    </td>
  </tr>
</table>

Device: Pixel 4 - A13
Magisk: 26.1 (renamed app: Magic)

Not sure what's not working here, other apps don't seem to be bothered, anyway it's not a huge deal as those two apps still works fine, the only concern it's that somehow they still detect root or root apps.

**Comment by adrianmmiller** [comment]
Hey there, this is the place to ask....

Firstly, when you say "blocked root detection through Hide My Applist **instead** of Magisk's denylist", i take this to mean that you havent added those apps to Magisk's Deny List (and preferably with Enforce Deny List OFF and Shamiko installed, and a reboot (and posibly clearing data of affected apps)), as thats still needed with HMA. 

HMA is really an additional step to the Deny List.

Secondly, even with apps added to the Deny List and Shamiko installed, some apps will still detect root as its a cat and mouse game where banks are using more sophisticated methods to detect the presence of root. While you can try and use an alternate fork of Magisk like Delta, which *can* sometimes manage to block detection where official can't, in the next major version of Official Magisk (v2.7), we're hoping new functionality will get Offical Magisk back to closer to being able to block as effectively as it once did....the early signs are encouraging.

Thirdly, this guide has been updated to hopefully make it easier to follow, though you seem to have done well, and also features the alternate to blacklist mode, whitelist mode, which some have found *can* work better for some sensitive apps.
The revamped guide has taken longer than planned to finalise, but its now curated/edited by 3 of us, as opposed to just me, and so we have spent a lot fo time discussing the format and content, but i hope it will be out this weekend. I will let you know if you like, though this guide will link to it at its new home. With the new guide, we decided to remove any links or mention of other Magisk forks after some debate, but that doesnt mean the steps wont work with them.

**Comment by NicolaSpadari** [comment]
Thanks for the quick response, yes for the first part I meant that Magisk enforce denylist is off, shamiko is installed, and of course I restarted the device.

I'll probably try Delta, meanwhile as I said it's not that bad of a situation since apps just prompt the text but still works as intended.

Anyway thank you for the effort on the guide, I'll keep the issue open so you can post a link/reply when the new guide will be out, no hurry, I appreciate it

**Comment by adrianmmiller** [comment]
New guide is out:

https://github.com/mModule/guide_hma

Please post any issues related to HMA there, thanks, theres 3 of us who contribute to it now...
